CREATE TABLE ABTEILUNG (
    ABT_ID        NUMBER(10)      PRIMARY KEY,
    NAME          VARCHAR2(100)   NOT NULL,
    STANDORT      VARCHAR2(100)
);

INSERT INTO ABTEILUNG (ABT_ID, NAME, STANDORT) VALUES (10, 'IT', 'Berlin');
INSERT INTO ABTEILUNG (ABT_ID, NAME, STANDORT) VALUES (20, 'Fertigung', 'München');
INSERT INTO ABTEILUNG (ABT_ID, NAME, STANDORT) VALUES (30, 'HR', 'Hamburg');

CREATE TABLE MITARBEITER (
    MIT_ID        NUMBER(10)      PRIMARY KEY,
    VORNAME       VARCHAR2(50)    NOT NULL,
    NACHNAME      VARCHAR2(50)    NOT NULL,
    GEHALT        NUMBER(10,2),
    ABT_ID        NUMBER(10),

    CONSTRAINT FK_MIT_ABT
        FOREIGN KEY (ABT_ID)
        REFERENCES ABTEILUNG (ABT_ID)
);

INSERT INTO MITARBEITER (MIT_ID, VORNAME, NACHNAME, GEHALT, ABT_ID)
VALUES (1, 'Anna', 'Schmidt', 52000, 10);

INSERT INTO MITARBEITER (MIT_ID, VORNAME, NACHNAME, GEHALT, ABT_ID)
VALUES (2, 'Max', 'Müller', 61000, 10);

INSERT INTO MITARBEITER (MIT_ID, VORNAME, NACHNAME, GEHALT, ABT_ID)
VALUES (3, 'Lisa', 'Klein', 45000, 20);

INSERT INTO MITARBEITER (MIT_ID, VORNAME, NACHNAME, GEHALT, ABT_ID)
VALUES (4, 'Tom', 'Berger', 40000, 30);
``
