CREATE TABLE ABTEILUNG (
    ABT_ID        NUMBER(15)      PRIMARY KEY,
    NAME          VARCHAR2(100)   NOT NULL,
    STANDORT      VARCHAR2(100)
);

CREATE TABLE MITARBEITER (
    MIT_ID        NUMBER(10)      PRIMARY KEY,
    VORNAME       VARCHAR2(50)    NOT NULL,
    NACHNAME      VARCHAR2(50)    NOT NULL,
    GEHALT        NUMBER(10,2),
    ABT_ID        NUMBER(10),

    CONSTRAINT FK_MIT_ABT
        FOREIGN KEY (ABT_ID)
        REFERENCES ABTEILUNG (ABT_ID)
);