CREATE TABLE ABTEILUNG (
    ABT_ID     INT            NOT NULL PRIMARY KEY,
    NAME       VARCHAR(200)   NOT NULL,
    STANDORT   VARCHAR(200)
);

CREATE TABLE MITARBEITER (
    MIT_ID     INT            NOT NULL PRIMARY KEY,
    VORNAME    VARCHAR(50)    NOT NULL,
    NACHNAME   VARCHAR(50)    NOT NULL,
    GEHALT     DECIMAL(10,2),
    ABT_ID     INT,

    CONSTRAINT FK_MIT_ABT
        FOREIGN KEY (ABT_ID)
            REFERENCES ABTEILUNG(ABT_ID)
);
