CREATE TABLE ABTEILUNG (
    ABT_ID     INT            NOT NULL PRIMARY KEY,
<<<<<<< HEAD
    NAME       VARCHAR(255)   NOT NULL,
=======
    NAME       VARCHAR(200)   NOT NULL,
>>>>>>> main
    STANDORT   VARCHAR(100)
);

CREATE TABLE MITARBEITER (
    MIT_ID     INT            NOT NULL PRIMARY KEY,
    VORNAME    VARCHAR(50)    NOT NULL,
    NACHNAME   VARCHAR(50)    NOT NULL,
    GEHALT     DECIMAL(10,2),
    ABT_ID     INT,
);
